Excluded:
  - test.cr

# Problems found: 7
# Run `ameba --only Naming/BlockParameterName` for details
Naming/BlockParameterName:
  Description: Disallows non-descriptive block parameter names
  MinNameLength: 3
  AllowNamesEndingInNumbers: true
  # Excluded:
  #   - src/cli/ast_web.cr
  #   - src/cli/prompt.cr
  #   - src/larimar/text_document.cr
  AllowedNames:
    - e
    - i
    - b
    - t
    - j
    - k
    - v
    - x
    - y
    - ex
    - io
    - ws
    - op
    - tx
    - id
    - ip
    - k1
    - k2
    - v1
    - v2
  ForbiddenNames: []
  Enabled: true
  Severity: Convention

# Problems found: 1
# Run `ameba --only Naming/QueryBoolMethods` for details
Naming/QueryBoolMethods:
  Enabled: false

# Problems found: 32
# Run `ameba --only Documentation/DocumentationAdmonition` for details
Documentation/DocumentationAdmonition:
  Description: Reports documentation admonitions
  Timezone: UTC
  Admonitions:
    - TODO
    - FIXME
    - BUG
  Enabled: false
  Severity: Warning

# Problems found: 6
# Run `ameba --only Lint/UselessAssign` for details
Lint/UselessAssign:
  Description: Disallows useless variable assignments
  ExcludeTypeDeclarations: false
  Excluded:
    - src/parser/parser.cr
    - src/parser/lexer.cr
    - src/larimar/analysis/semantic_tokens_visitor.cr
    - src/larimar/controllers/parser_controller.cr
    - src/larimar/controllers/crystal_controller.cr
  Enabled: true
  Severity: Warning

# Problems found: 16
# Run `ameba --only Metrics/CyclomaticComplexity` for details
Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 100
  Excluded:
    - src/parser/parser.cr
    - src/parser/lexer.cr
    - src/larimar/analysis/document_symbols_visitor.cr
    - src/larimar/controllers/parser_controller.cr
  Enabled: true
  Severity: Warning

# Problems found: 5
# Run `ameba --only Style/ParenthesesAroundCondition` for details
Style/ParenthesesAroundCondition:
  Description: Disallows redundant parentheses around control expressions
  ExcludeTernary: false
  AllowSafeAssignment: true
  Enabled: true
  Severity: Convention

# Problems found: 13
# Run `ameba --only Style/WhileTrue` for details
Style/WhileTrue:
  Description: Disallows while statements with a true literal as condition
  Excluded:
    - src/parser/parser.cr
  Enabled: true
  Severity: Convention

# Problems found: 1
# Run `ameba --only Lint/NotNil` for details
Lint/NotNil:
  Description: Identifies usage of `not_nil!` calls
  Enabled: true
  Severity: Warning

# Problems found: 1
# Run `ameba --only Lint/UnusedArgument` for details
Lint/UnusedArgument:
  Description: Disallows unused arguments
  IgnoreDefs: true
  IgnoreBlocks: false
  IgnoreProcs: false
  Excluded:
    - src/larimar/controllers/parser_controller.cr
  Enabled: true
  Severity: Warning

# Problems found: 1
# Run `ameba --only Performance/FlattenAfterMap` for details
Performance/FlattenAfterMap:
  Description: Identifies usage of `flatten` calls that follow `map`
  Excluded:
    - src/larimar/controllers/crystal_controller.cr
  Enabled: true
  Severity: Warning
