on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install Deps
        run: |
          sudo apt-get install -y \
            automake \
            build-essential \
            git \
            libbsd-dev \
            libevent-dev \
            libgmp-dev \
            libgmpxx4ldbl \
            libpcre2-dev \
            libssl-dev \
            libtool \
            libxml2-dev \
            libyaml-dev \
            lld \
            llvm \
            llvm-dev\
            libz-dev
      - name: Install Shards
        run: shards install
      - name: Run tests
        run: crystal spec
